---
title: "Crop and adjust MODIS"
author: "Robert Paul, Jeff Stephens"
date: "June 24, 2016"
output: html_document
---

## Load libraries
```{r load-libs}
library(raster)
library(rgdal)
library(RCurl)
library(foreach)
```

## Functions

```{r functions}
crop_files_to_extent <- function(path, modis_ext) {
  # Save current working directory
  origwd <- getwd()
  
  # Move into path for working directory
  setwd(path)
  
  # Prepare the directory for the processed rasters
  dir.create("processed", showWarnings = FALSE)
  # List of GeoTIFFs in folder
  files <- dir(pattern = "*.tif$")
  
  # Get each raster in the path
  foreach(i = 1:length(files))  %do% {
    # Load file
    raster <- raster(files[i])
    # Crop it
    raster <- crop(raster, modis_ext)
    # Scale values
    raster  <- raster * 0.0001
    # Save it
    newname <- paste0("processed/proc_", files[i])
    print(paste("Writing", newname))
    writeRaster(raster,
                filename = newname,
                format = "GTiff",
                overwrite = TRUE)
    }
  # Return to original working directory
  setwd(origwd)
}
```

```{r pull-down-data}
# Download the data if it's not found
if(length(dir("data")) == 0) {
  # Move to the data directory
  setwd("data")
  # ***Change this to where MRT is installed!
  mrt_path <- "/Users/exnihilo/Applications/bin/"
  # ***Change to where the MRT application data folder is!
  Sys.setenv(MRT_DATA_DIR="/Users/exnihilo/Applications/data/")
  # NDVI and EVI are bands 1 and 2 of 12
  getBands <- c(1, 1, rep(0, 10))
  # bands_subset weirdly expects a single string--"1 1 0 0 0..."
  getBands <- paste(getBands, collapse = " ")
  # Download MODIS data and reproject it to UTM 18
  ModisDownload(x = 1,
                h = 12,
                v = 4,
                dates=c("2013.01.01", "2013.12.30"),
                proj=T,
                proj_type="UTM",
                utm_zone=18,
                datum="WGS84",
                pixel_size=250,
                bands_subset = getBands,
                MRTpath= mrt_path)
  
  # Move files into their respective folders
  # This would be a candidate for refactoring into a function, but
  # I just want to get this done.
  filestocopy <- list.files(pattern="EVI")
  targetdir <- "2013/evi"
  file.copy(from=filestocopy,
            to=targetdir,
            recursive = FALSE,
            copy.mode = TRUE)
  file.remove(filestocopy)
  
  filestocopy <- list.files(pattern="NDVI")
  targetdir <- "2013/ndvi"
  file.copy(from=filestocopy,
            to=targetdir,
            recursive = FALSE,
            copy.mode = TRUE)
  file.remove(filestocopy)
  # Move back to the root working directory
  setwd("../")
}
```

## Save rasters with cropped extents and scaling-adjusted index values 
```{r crop-extents}
# UTM Zone 18 coords for area of interest, hard-coded
modis_ext  <- extent(554358, 774977, 4617867, 4761525)
crop_files_to_extent("data/2013/ndvi", modis_ext)
crop_files_to_extent("data/2013/evi", modis_ext)
```


